import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'net.darkhax.curseforgegradle' version '1.1.27'
	id "com.modrinth.minotaur" version "2.+"
}

version = project.minecraft_version + "-" + project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	maven {
		name = "Jared's maven"
		url = "https://maven.blamejared.com/"
	}
	maven {
		name = "ModMaven"
		url = "https://modmaven.dev"
	}
}

loom {
    splitEnvironmentSourceSets()
    mods {
        "nemos-carpentry" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

fabricApi {
    configureDataGeneration {
        client = true
        modId = project.mod_id
        outputDirectory = file("src/main/generated")
        addToResources = true
    }
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	compileOnly "org.jetbrains:annotations:26.1.0"
	clientCompileOnly "mezz.jei:jei-${project.minecraft_version}-fabric-api:${project.jei_version}"
	clientRuntimeOnly "mezz.jei:jei-${project.minecraft_version}-fabric:${project.jei_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(25)
	// Publish the original, unobfuscated source and jar artifacts.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
	dependsOn(tasks.jar)
	apiToken = System.getenv("CURSEFORGE_TOKEN")

	def projectId = findProperty('curseforge_project_id')

	def mainFile = upload(projectId, tasks.jar.archiveFile)
	mainFile.changelog = file('Changelog.md')
	mainFile.displayName = findProperty('mod_name') + ' ' + findProperty('version')
	mainFile.releaseType = 'release'
	mainFile.addGameVersion(project.minecraft_version)
	mainFile.addModLoader('Fabric')
	mainFile.addEnvironment('Client', 'Server')
	mainFile.addJavaVersion('Java 25')
}

modrinth {
	token.set(System.getenv("MODRINTH_TOKEN"))
	projectId.set(findProperty('modrinth_project_id'))
	changelog.set(file('Changelog.md').text)
	versionName.set(findProperty('mod_name') + ' ' + findProperty('version'))
	versionType.set("release")
	gameVersions = [project.minecraft_version]
	loaders = ["fabric"]
	uploadFile.set(tasks.jar)
	dependencies {
		required.project("fabric-api")
		optional.project("jei")
	}
}
tasks.modrinth.dependsOn(tasks.jar)
