# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.19.2
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=4.0.3
maven_group=com.nemonotfound
archives_base_name=nemos-carpentry
mod_id=nemos-carpentry
mod_name=Nemo's Carpentry

# Dependencies
fabric_version=0.141.4+1.21.11
jei_version=27.4.0.22

# Upload
curseforge_project_id=928372
modrinth_project_id=nemos-carpentry
