package com.nemonotfound.nemos.carpentry.datagen;

import com.nemonotfound.nemos.carpentry.block.CarpentryBlocks;
import com.nemonotfound.nemos.carpentry.block.enums.BenchPart;
import com.nemonotfound.nemos.carpentry.block.enums.ChairPart;
import com.nemonotfound.nemos.carpentry.block.seats.ParkBenchBlock;
import com.nemonotfound.nemos.carpentry.property.CarpentryBlockStateProperties;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootSubProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.storage.loot.LootTable;

import java.util.concurrent.CompletableFuture;

public class LootTableGenerator extends FabricBlockLootSubProvider {

    public LootTableGenerator(FabricPackOutput dataOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        this.dropSelf(CarpentryBlocks.ACACIA_LADDER);
        this.dropSelf(CarpentryBlocks.BAMBOO_LADDER);
        this.dropSelf(CarpentryBlocks.BOUND_BAMBOO_LADDER);
        this.dropSelf(CarpentryBlocks.BIRCH_LADDER);
        this.dropSelf(CarpentryBlocks.CHERRY_LADDER);
        this.dropSelf(CarpentryBlocks.CRIMSON_LADDER);
        this.dropSelf(CarpentryBlocks.DARK_OAK_LADDER);
        this.dropSelf(CarpentryBlocks.PALE_OAK_LADDER);
        this.dropSelf(CarpentryBlocks.JUNGLE_LADDER);
        this.dropSelf(CarpentryBlocks.MANGROVE_LADDER);
        this.dropSelf(CarpentryBlocks.SPRUCE_LADDER);
        this.dropSelf(CarpentryBlocks.WARPED_LADDER);

        this.dropSelf(CarpentryBlocks.ACACIA_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.BAMBOO_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.BIRCH_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.CHERRY_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.CRIMSON_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.DARK_OAK_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.PALE_OAK_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.JUNGLE_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.MANGROVE_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.OAK_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.SPRUCE_TABLE_THE_CLASSIC);
        this.dropSelf(CarpentryBlocks.WARPED_TABLE_THE_CLASSIC);

        this.dropSelf(CarpentryBlocks.ACACIA_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.BAMBOO_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.BIRCH_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.CHERRY_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.CRIMSON_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.DARK_OAK_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.PALE_OAK_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.JUNGLE_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.MANGROVE_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.OAK_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.SPRUCE_COFFEE_TABLE_PASCAL);
        this.dropSelf(CarpentryBlocks.WARPED_COFFEE_TABLE_PASCAL);

        this.dropSelf(CarpentryBlocks.ACACIA_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.BAMBOO_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.BIRCH_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.CHERRY_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.CRIMSON_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.DARK_OAK_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.PALE_OAK_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.JUNGLE_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.MANGROVE_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.OAK_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.SPRUCE_STANDING_TABLE);
        this.dropSelf(CarpentryBlocks.WARPED_STANDING_TABLE);

        this.dropSelf(CarpentryBlocks.ACACIA_CHAIR);
        this.dropSelf(CarpentryBlocks.BAMBOO_CHAIR);
        this.dropSelf(CarpentryBlocks.BIRCH_CHAIR);
        this.dropSelf(CarpentryBlocks.CHERRY_CHAIR);
        this.dropSelf(CarpentryBlocks.CRIMSON_CHAIR);
        this.dropSelf(CarpentryBlocks.DARK_OAK_CHAIR);
        this.dropSelf(CarpentryBlocks.PALE_OAK_CHAIR);
        this.dropSelf(CarpentryBlocks.JUNGLE_CHAIR);
        this.dropSelf(CarpentryBlocks.MANGROVE_CHAIR);
        this.dropSelf(CarpentryBlocks.OAK_CHAIR);
        this.dropSelf(CarpentryBlocks.SPRUCE_CHAIR);
        this.dropSelf(CarpentryBlocks.WARPED_CHAIR);

        this.dropSelf(CarpentryBlocks.ACACIA_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.BAMBOO_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.BIRCH_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.CHERRY_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.CRIMSON_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.DARK_OAK_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.PALE_OAK_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.JUNGLE_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.MANGROVE_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.OAK_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.SPRUCE_CHAIR_FELIX);
        this.dropSelf(CarpentryBlocks.WARPED_CHAIR_FELIX);

        this.add(CarpentryBlocks.ACACIA_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.BAMBOO_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.BIRCH_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.CHERRY_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.CRIMSON_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.DARK_OAK_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.PALE_OAK_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.JUNGLE_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.MANGROVE_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.OAK_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.SPRUCE_PARK_BENCH, this::benchDrops);
        this.add(CarpentryBlocks.WARPED_PARK_BENCH, this::benchDrops);

        this.add(CarpentryBlocks.ACACIA_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.OAK_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_CHAIR_LUKAS, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_CHAIR_LUKAS, this::chairDrops);

        this.add(CarpentryBlocks.ACACIA_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_CHAIR_LUKAS_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_CHAIR_LUKAS_NATURAL, this::chairDrops);

        this.add(CarpentryBlocks.ACACIA_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.OAK_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_CHAIR_TOMMY, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_CHAIR_TOMMY, this::chairDrops);

        this.add(CarpentryBlocks.ACACIA_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_CHAIR_TOMMY_NATURAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_CHAIR_TOMMY_NATURAL, this::chairDrops);

        this.add(CarpentryBlocks.ACACIA_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.OAK_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_CHAIR_GREGORY, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_CHAIR_GREGORY, this::chairDrops);
        
        this.add(CarpentryBlocks.ACACIA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.ACACIA_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BAMBOO_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.BIRCH_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CHERRY_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.CRIMSON_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.DARK_OAK_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.PALE_OAK_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.JUNGLE_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.MANGROVE_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.OAK_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.SPRUCE_PINK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_WHITE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_LIGHT_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_GRAY_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_BLACK_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_BROWN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_RED_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_ORANGE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_YELLOW_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_LIME_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_GREEN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_CYAN_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_LIGHT_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_BLUE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_PURPLE_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_MAGENTA_CHAIR_PASCAL, this::chairDrops);
        this.add(CarpentryBlocks.WARPED_PINK_CHAIR_PASCAL, this::chairDrops);
        
        this.dropSelf(CarpentryBlocks.WHITE_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.LIGHT_GRAY_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.GRAY_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.BLACK_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.BROWN_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.RED_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.ORANGE_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.YELLOW_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.LIME_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.GREEN_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.CYAN_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.LIGHT_BLUE_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.BLUE_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.PURPLE_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.MAGENTA_BARBER_CHAIR);
        this.dropSelf(CarpentryBlocks.PINK_BARBER_CHAIR);

        this.dropSelf(CarpentryBlocks.WHITE_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.LIGHT_GRAY_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.GRAY_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.BLACK_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.BROWN_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.RED_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.ORANGE_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.YELLOW_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.LIME_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.GREEN_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.CYAN_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.LIGHT_BLUE_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.BLUE_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.PURPLE_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.MAGENTA_BAR_CHAIR);
        this.dropSelf(CarpentryBlocks.PINK_BAR_CHAIR);

        this.dropSelf(CarpentryBlocks.ACACIA_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.BAMBOO_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.BIRCH_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.CHERRY_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.CRIMSON_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.DARK_OAK_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.PALE_OAK_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.JUNGLE_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.MANGROVE_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.OAK_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.SPRUCE_COFFEE_TABLE);
        this.dropSelf(CarpentryBlocks.WARPED_COFFEE_TABLE);

        this.dropSelf(CarpentryBlocks.ACACIA_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.BAMBOO_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.BIRCH_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.CHERRY_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.CRIMSON_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.DARK_OAK_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.PALE_OAK_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.JUNGLE_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.MANGROVE_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.OAK_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.SPRUCE_BARREL_SEAT);
        this.dropSelf(CarpentryBlocks.WARPED_BARREL_SEAT);
    }

    private LootTable.Builder benchDrops(Block block) {
        return this.createSinglePropConditionTable(block, ParkBenchBlock.PART, BenchPart.LEFT);
    }

    private LootTable.Builder chairDrops(Block block) {
        return this.createSinglePropConditionTable(block, CarpentryBlockStateProperties.CHAIR_PART, ChairPart.LOWER);
    }
}
